site_name: Olga Kirpichenko
site_url: https://OlyaOlya2608.github.io/CV_test/
theme:
  name: material
  features:
    - content.tooltips
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - abbr
  - attr_list
  - pymdownx.snippets
nav:
  - Обо мне: index.md
  - Пример инструкции: instruction.md
